(function(){
const D=window.ST_MICHAELS_DATA;if(!D)return;
const pct=v=>`${((+v||0)*100).toFixed(2)}%`,num=v=>Math.round(+v||0),ratio=v=>(+v||0).toFixed(1),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),arg=s=>encodeURIComponent(String(s)).replace(/'/g,'%27');
const sortBy=fn=>D.players.slice().sort((a,b)=>fn(b)-fn(a)),ko=D.kickoutTotals,t=D.team;
const scoring=sortBy(p=>p.scores),possession=sortBy(p=>p.turnoversWon),bestRatio=D.players.filter(p=>p.negative>0).slice().sort((a,b)=>(b.positive/b.negative)-(a.positive/a.negative))[0];
function bar(label,value,cls=''){return `<div class="bar-row"><span>${label}</span><div class="track"><div class="fill ${cls}" style="width:${Math.min(100,value*100)}%"></div></div><b>${pct(value)}</b></div>`}
function leader(label,p,value,unit,detail,mode){return `<div class="leader click-row" onclick="openPlayer(decodeURIComponent('${arg(p.name)}'),'${mode}')"><span class="rank">${label}</span><strong>${esc(p.name)}</strong><span class="score">${value}</span><small>${unit} • ${detail}</small></div>`}

document.querySelector('#home').innerHTML=`<div class="cards"><div class="card kpi green"><div class="eyebrow">Shot conversion</div><div class="value">${pct(t.conversion)}</div><div class="meta">${num(t.scores)} scores from ${num(t.shots)} shots</div></div><div class="card kpi gold"><div class="eyebrow">Turnover differential</div><div class="value">${t.differential>=0?'+':''}${num(t.differential)}</div><div class="meta">${num(t.turnoversWon)} won • ${num(t.lost)} lost</div></div><div class="card kpi"><div class="eyebrow">Turnover %</div><div class="value">${pct(t.security)}</div><div class="meta">Turnovers Won v Lost</div></div><div class="card kpi"><div class="eyebrow">Own short retention</div><div class="value">${pct(ko.ownShort.rate)}</div><div class="meta">${num(ko.ownShort.won)} won from ${num(ko.ownShort.taken)}</div></div></div>
<div class="grid"><div class="panel"><div class="panel-head"><h2>Statistical leaders</h2><button class="link" data-go="players">All player data →</button></div><div class="leaders">${leader('Most scores',scoring[0],num(scoring[0].scores),'scores',`${num(scoring[0].shots)} shots • ${pct(scoring[0].conversion)}`,'scoring')}${leader('Most turnovers won',possession[0],num(possession[0].turnoversWon),'won',`${num(possession[0].lost)} lost • ${possession[0].turnoversWon-possession[0].lost>=0?'+':''}${num(possession[0].turnoversWon-possession[0].lost)} differential`,'possession')}${leader('Best P:N Ratio',bestRatio,ratio(bestRatio.positive/bestRatio.negative),'ratio',`${num(bestRatio.positive)} positive • ${num(bestRatio.negative)} negative`,'overview')}</div></div><div class="panel school-card"><h2>St Michaels</h2><p>A separate performance hub in the school colours. Current match data is temporary and ready to be replaced.</p><img src="st-michaels-crest.png" alt="St Michaels school crest"></div></div>
<div class="grid"><div class="panel"><div class="panel-head"><h2>Latest match records</h2><button class="link" data-go="matches">All matches →</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Match</th><th>Conversion</th><th>Turnover diff.</th></tr></thead><tbody>${D.matches.slice(-5).reverse().map(m=>`<tr class="click-row" onclick="openMatch(decodeURIComponent('${arg(m.name)}'))"><td>${esc(m.name)}</td><td>${pct(m.conversion)}</td><td>${m.differential>=0?'+':''}${num(m.differential)}</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-head"><h2>Kickout snapshot</h2><button class="link" data-go="kickouts">Explore →</button></div><div class="bars">${bar('Own short',ko.ownShort.rate,'green')}${bar('Own long',ko.ownLong.rate)}${bar('Opp. short won',ko.oppShort.rate,'gold')}${bar('Opp. long won',ko.oppLong.rate,'gold')}</div></div></div>`;

document.querySelector('#opposition').innerHTML=`<div class="panel"><div class="empty"><h2>Opposition Analysis</h2><p>This section is ready for the dedicated opposition-analysis spreadsheet.</p><p class="meta">No opposition statistics are displayed until that source is provided and validated.</p></div></div>`;

const playerSort={overview:{index:2,dir:'desc'},scoring:{index:1,dir:'desc'},possession:{index:1,dir:'desc'},defence:{index:1,dir:'desc'}};
let selectedPlayer='';
function renderPlayers(mode='overview',selected){
 const cfg={overview:{title:'Player overview',heads:['Player','Matches','Positive','Negative','P:N Ratio'],values:p=>[p.name,p.matches,p.positive,p.negative,p.negative?p.positive/p.negative:-1],cells:p=>[p.name,p.matches,num(p.positive),num(p.negative),p.negative?ratio(p.positive/p.negative):'—']},scoring:{title:'Scoring output',heads:['Player','Scores','Wides','Short','Shots','Conversion'],values:p=>[p.name,p.scores,p.wides,p.short,p.shots,p.conversion],cells:p=>[p.name,num(p.scores),num(p.wides),num(p.short),num(p.shots),pct(p.conversion)]},possession:{title:'Turnovers',heads:['Player','Won','Lost','Differential','Turnover %'],values:p=>[p.name,p.turnoversWon,p.lost,p.turnoversWon-p.lost,p.security],cells:p=>[p.name,num(p.turnoversWon),num(p.lost),`${p.turnoversWon-p.lost>=0?'+':''}${num(p.turnoversWon-p.lost)}`,pct(p.security)]},defence:{title:'Blocks & Tackles',heads:['Player','Interceptions / Tackles','Blocks'],values:p=>[p.name,p.interceptionsTackles,p.blocks],cells:p=>[p.name,num(p.interceptionsTackles),num(p.blocks)]}};
 const c=cfg[mode]||cfg.overview,s=playerSort[mode],direction=s.dir==='asc'?1:-1;
 const pool=D.players.slice().sort((a,b)=>{const av=c.values(a)[s.index],bv=c.values(b)[s.index];return typeof av==='string'?direction*av.localeCompare(bv):direction*(av-bv)||a.name.localeCompare(b.name)});
 selectedPlayer=selected||selectedPlayer||pool[0].name;const p=D.players.find(x=>x.name===selectedPlayer)||pool[0];selectedPlayer=p.name;
 document.querySelector('#players').innerHTML=`<div class="tabbar">${[['overview','Overview'],['scoring','Scoring'],['possession','Possession'],['defence','Blocks & Tackles']].map(x=>`<button class="${x[0]===mode?'on':''}" onclick="renderPlayers('${x[0]}')">${x[1]}</button>`).join('')}</div><div class="detail-grid"><div class="panel"><div class="panel-head"><h2>${c.title}</h2><span class="eyebrow">Click a heading to sort</span></div><div class="table-wrap"><table class="table"><thead><tr>${c.heads.map((h,i)=>`<th><button class="sort-head ${s.index===i?'active':''}" onclick="sortPlayers('${mode}',${i})">${h}<span>${s.index===i?(s.dir==='asc'?'▲':'▼'):'↕'}</span></button></th>`).join('')}</tr></thead><tbody>${pool.map(x=>`<tr class="click-row" onclick="renderPlayers('${mode}',decodeURIComponent('${arg(x.name)}'))">${c.cells(x).map((v,i)=>`<td>${i?esc(v):`<b>${esc(v)}</b>`}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-head"><h2>${esc(p.name)}</h2><span class="pill blue">${p.matches} matches</span></div><div class="stat-grid"><div class="stat-box"><b>${num(p.scores)}/${num(p.shots)}</b><span>Scores / shots</span></div><div class="stat-box"><b>${pct(p.conversion)}</b><span>Conversion</span></div><div class="stat-box"><b>${pct(p.security)}</b><span>Turnover %</span></div><div class="stat-box"><b>${num(p.turnoversWon)}</b><span>Turnovers won</span></div><div class="stat-box"><b>${num(p.lost)}</b><span>Turnovers lost</span></div><div class="stat-box"><b>${num(p.interceptionsTackles)}</b><span>Interceptions / tackles</span></div><div class="stat-box"><b>${num(p.blocks)}</b><span>Blocks</span></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Match</th><th>Scores</th><th>Shots</th><th>Won</th><th>Lost</th><th>Positive</th></tr></thead><tbody>${p.games.map(g=>`<tr><td>${esc(g.match)}</td><td>${num(g.scores)}</td><td>${num(g.shots)}</td><td>${num(g.turnoversWon)}</td><td>${num(g.lost)}</td><td>${num(g.positive)}</td></tr>`).join('')}</tbody></table></div></div></div>`;
}
window.sortPlayers=(mode,index)=>{const s=playerSort[mode];s.dir=s.index===index&&s.dir==='desc'?'asc':'desc';s.index=index;renderPlayers(mode,selectedPlayer)};
window.renderPlayers=renderPlayers;window.openPlayer=(name,mode='overview')=>{show('players');renderPlayers(mode,name)};
function renderMatches(selected){const m=D.matches.find(x=>x.name===selected)||D.matches[D.matches.length-1];document.querySelector('#matches').innerHTML=`<div class="detail-grid"><div class="panel"><div class="panel-head"><h2>Match records</h2><span class="eyebrow">${D.matches.length} matches</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Match</th><th>Conversion</th><th>TO diff.</th></tr></thead><tbody>${D.matches.map(x=>`<tr class="click-row" onclick="renderMatches(decodeURIComponent('${arg(x.name)}'))"><td>${esc(x.name)}</td><td>${pct(x.conversion)}</td><td>${x.differential>=0?'+':''}${num(x.differential)}</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-head"><div><h2>${esc(m.name)}</h2><div class="meta">${esc(m.date)}</div></div><span class="pill blue">${m.players.length} listed</span></div><div class="stat-grid"><div class="stat-box"><b>${pct(m.conversion)}</b><span>Conversion</span></div><div class="stat-box"><b>${num(m.scores)}/${num(m.shots)}</b><span>Scores / shots</span></div><div class="stat-box"><b>${m.differential>=0?'+':''}${num(m.differential)}</b><span>TO differential</span></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Player</th><th>Scores</th><th>Shots</th><th>Won</th><th>Lost</th></tr></thead><tbody>${m.players.filter(p=>p.scores+p.shots+p.turnoversWon+p.lost+p.positive+p.negative>0).sort((a,b)=>b.positive-a.positive).map(p=>`<tr><td>${esc(p.name)}</td><td>${num(p.scores)}</td><td>${num(p.shots)}</td><td>${num(p.turnoversWon)}</td><td>${num(p.lost)}</td></tr>`).join('')}</tbody></table></div></div></div>`}
window.renderMatches=renderMatches;window.openMatch=name=>{show('matches');renderMatches(name)};
document.querySelector('#kickouts').innerHTML=`<div class="cards">${[['Own short retention',ko.ownShort,'green'],['Own long retention',ko.ownLong,''],['Opp. short won',ko.oppShort,'gold'],['Opp. long won',ko.oppLong,'gold']].map(x=>`<div class="card kpi ${x[2]}"><div class="eyebrow">${x[0]}</div><div class="value">${pct(x[1].rate)}</div><div class="meta">${num(x[1].won)} / ${num(x[1].taken)}</div></div>`).join('')}</div><div class="panel" style="margin-top:18px"><div class="panel-head"><h2>Kickouts by match</h2><span class="eyebrow">${D.kickouts.length} matches</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Opponent</th><th>Goalkeeper</th><th>Own short</th><th>Own long</th><th>Opp. short won</th><th>Opp. long won</th></tr></thead><tbody>${D.kickouts.map(k=>`<tr><td>${esc(k.opponent)}</td><td>${esc(k.goalkeeper)}</td><td>${pct(k.ownShort.rate)} <span class="meta">(${num(k.ownShort.won)}/${num(k.ownShort.taken)})</span></td><td>${pct(k.ownLong.rate)} <span class="meta">(${num(k.ownLong.won)}/${num(k.ownLong.taken)})</span></td><td>${pct(k.oppShort.rate)} <span class="meta">(${num(k.oppShort.won)}/${num(k.oppShort.taken)})</span></td><td>${pct(k.oppLong.rate)} <span class="meta">(${num(k.oppLong.won)}/${num(k.oppLong.taken)})</span></td></tr>`).join('')}</tbody></table></div></div>`;
document.querySelector('#analysis').innerHTML=`<div class="detail-grid"><div class="panel"><div class="panel-head"><h2>Shot conversion</h2><b>${pct(t.conversion)}</b></div><div class="bars">${bar('Scores',t.scores/t.shots,'green')}${bar('Wides',t.wides/t.shots,'gold')}${bar('Dropped short',t.short/t.shots)}</div><div class="stat-grid"><div class="stat-box"><b>${num(t.scores)}</b><span>Scores</span></div><div class="stat-box"><b>${num(t.wides)}</b><span>Wides</span></div><div class="stat-box"><b>${num(t.short)}</b><span>Dropped short</span></div></div><div class="formula">Total Shots = Scores + Wides + Dropped Short<br>Conversion = Scores ÷ Total Shots</div></div><div class="panel"><div class="panel-head"><h2>Turnover analysis</h2><b>${t.differential>=0?'+':''}${num(t.differential)}</b></div><div class="bars">${bar('Won',1,'green')}${bar('Lost',t.turnoversWon?t.lost/t.turnoversWon:0,'gold')}</div><div class="stat-grid"><div class="stat-box"><b>${num(t.turnoversWon)}</b><span>Won</span></div><div class="stat-box"><b>${num(t.lost)}</b><span>Lost</span></div><div class="stat-box"><b>${pct(t.security)}</b><span>Turnover %</span></div></div><div class="formula">Lost = Given Away + Dispossessed + Dropped Short<br>Turnover % = Won ÷ (Won + Lost)<br>Turnovers Won v Lost</div></div></div>`;
renderPlayers();renderMatches();
})();
